# -*- coding: utf-8 -*-
"""final1150120.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/180inZLkL0tUz9rCraHnUMjSxzKMI-bNq
"""

# 1. 安裝 Selenium
!pip install selenium

# 2. 下載並安裝 Google Chrome 官方穩定版 (由 Google 伺服器直接下載，確保完整)
!wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
!apt-get install -y ./google-chrome-stable_current_amd64.deb

# 3. 自動修正依賴關係 (這是解決 Status Code 1 的關鍵)
!apt-get -f install -y

# 4. 安裝中文字型
!apt-get install -y fonts-noto-cjk

# 5. 清理殘存檔
!rm google-chrome-stable_current_amd64.deb

print("環境安裝完成！請繼續執行下一步。")

from google.colab import drive
import os

# 掛載雲端硬碟
drive.mount('/content/drive')

# 確認檔案是否存在 (這行是為了檢查用，確保路徑沒打錯)
file_path = '/content/drive/MyDrive/Colab Notebooks/123.txt'
if os.path.exists(file_path):
    print(f"✅ 檔案讀取成功：{file_path}")
else:
    print(f"❌ 找不到檔案，請檢查路徑")

import time
import base64
import os
import smtplib
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText
from email.mime.application import MIMEApplication
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC

# ================= 設定區 =================
# 1. 指定您的 txt 檔案路徑
txt_file_path = '/content/drive/MyDrive/Colab Notebooks/123.txt'

# 2. 設定 Email 資訊
gmail_user = '您的Gmail帳號@gmail.com'
gmail_password = '您的應用程式專用密碼'
to_email = '您的公司信箱@company.com'
# ==========================================

# --- 啟動瀏覽器 (只啟動一次，節省時間) ---
options = webdriver.ChromeOptions()
options.add_argument('--headless')
options.add_argument('--no-sandbox')
options.add_argument('--disable-dev-shm-usage')
options.add_argument('--disable-gpu')
options.add_argument('--window-size=1920,1080')
options.add_argument('--remote-debugging-port=9222')

try:
    driver = webdriver.Chrome(options=options)
    print("✅ 瀏覽器啟動成功！準備開始批次作業...")
except:
    options.binary_location = "/usr/bin/google-chrome"
    driver = webdriver.Chrome(options=options)
    print("✅ 瀏覽器啟動成功 (備用模式)！")

try:
    # 讀取 txt 檔案中的每一行
    with open(txt_file_path, 'r', encoding='utf-8') as f:
        lines = f.readlines()

    # --- 開始大迴圈：一行一行執行 ---
    for batch_index, line in enumerate(lines):
        query_numbers = line.strip() # 去除換行符號

        # 如果是空行就跳過
        if not query_numbers:
            continue

        print(f"\n==========================================")
        print(f"🚀 正在執行第 {batch_index + 1} 批次")
        print(f"📋 統編清單: {query_numbers}")
        print(f"==========================================")

        generated_pdfs = [] # 清空 PDF 清單，準備存這一批的

        # [動作 A] 搜尋與下載
        try:
            driver.get("https://findbiz.nat.gov.tw/fts/query/QueryBar/queryInit.do")
            wait = WebDriverWait(driver, 20)

            # 1. 切換模式
            try:
                btn = wait.until(EC.presence_of_element_located((By.XPATH, "//label[contains(text(),'多統編查詢')]")))
                driver.execute_script("arguments[0].click();", btn)
                time.sleep(1)
            except:
                pass

            # 2. 勾選 [公司] 與 [商業]
            try:
                cmpy_box = driver.find_element(By.XPATH, "//input[@value='isCmpy']")
                if not cmpy_box.is_selected(): driver.execute_script("arguments[0].click();", cmpy_box)

                bus_box = driver.find_element(By.XPATH, "//input[@value='isBus']")
                if not bus_box.is_selected(): driver.execute_script("arguments[0].click();", bus_box)
            except:
                pass

            # 3. 輸入統編並搜尋
            input_box = wait.until(EC.presence_of_element_located((By.ID, "qryCond")))
            input_box.clear()
            input_box.send_keys(query_numbers)

            search_btn = driver.find_element(By.ID, "qryBtn")
            driver.execute_script("arguments[0].click();", search_btn)

            time.sleep(5) # 等待資料載入

            # 4. 定位資料
            target_elements = driver.find_elements(By.XPATH, "//*[contains(text(), '統一編號')]/ancestor::tr//a | //*[contains(text(), '統一編號')]/ancestor::div[contains(@class, 'panel')]//a")
            valid_links_indices = [i for i, elem in enumerate(target_elements) if len(elem.text) > 4]

            # 備用定位
            if not valid_links_indices:
                all_links = driver.find_elements(By.TAG_NAME, "a")
                valid_links_indices = [i for i, elem in enumerate(all_links) if len(elem.text) > 5 and "更多" not in elem.text and "指南" not in elem.text]

            print(f"   -> 本批次找到 {len(valid_links_indices)} 筆資料，開始下載...")

            # 5. 下載迴圈
            count = 0
            for _ in valid_links_indices:
                count += 1
                try:
                    # 重新定位
                    current_targets = driver.find_elements(By.XPATH, "//*[contains(text(), '統一編號')]/ancestor::tr//a | //*[contains(text(), '統一編號')]/ancestor::div[contains(@class, 'panel')]//a")
                    if not current_targets:
                        current_targets = [x for x in driver.find_elements(By.TAG_NAME, "a") if len(x.text) > 5 and "更多" not in x.text]

                    if count <= len(current_targets):
                        target = current_targets[count-1]
                        company_name = target.text # 抓取公司名稱方便辨識
                        driver.execute_script("arguments[0].click();", target)
                        time.sleep(4)

                        # 檔名加入批次編號，避免重複
                        filename = f"Batch{batch_index+1}_{company_name}.pdf"
                        # 處理檔名中可能有的非法字元
                        filename = "".join([c for c in filename if c.isalpha() or c.isdigit() or c in ' ._-']).rstrip()

                        print_options = {
                            'landscape': False, 'displayHeaderFooter': False, 'printBackground': True,
                            'preferCSSPageSize': True, 'paperWidth': 8.27, 'paperHeight': 11.69
                        }
                        result = driver.execute_cdp_cmd("Page.printToPDF", print_options)

                        with open(filename, "wb") as f:
                            f.write(base64.b64decode(result['data']))

                        generated_pdfs.append(filename)
                        print(f"      [v] 已下載: {filename}")

                        driver.back()
                        time.sleep(2)
                except Exception as e:
                    print(f"      [x] 下載失敗: {e}")
                    driver.back()
                    time.sleep(2)

        except Exception as e:
            print(f"   ⚠️ 本批次搜尋發生錯誤: {e}")

        # [動作 B] 寄送 Email (針對這一批)
        if generated_pdfs:
            print(f"   📧 正在寄送第 {batch_index + 1} 批次的 Email...")
            msg = MIMEMultipart()
            msg['Subject'] = f'商工登記查詢結果 - 第 {batch_index + 1} 批 (共 {len(generated_pdfs)} 筆)'
            msg['From'] = gmail_user
            msg['To'] = to_email

            body = f"這是自動化程式執行的第 {batch_index + 1} 批次查詢結果。\n查詢統編：{query_numbers}\n\n附件包含：\n" + "\n".join(generated_pdfs)
            msg.attach(MIMEText(body, 'plain'))

            for pdf_file in generated_pdfs:
                with open(pdf_file, "rb") as f:
                    attach = MIMEApplication(f.read(), _subtype="pdf")
                    attach.add_header('Content-Disposition', 'attachment', filename=pdf_file)
                    msg.attach(attach)

            try:
                server = smtplib.SMTP('smtp.gmail.com', 587)
                server.starttls()
                server.login(gmail_user, gmail_password)
                server.send_message(msg)
                server.quit()
                print("   ✅ Email 寄送成功！")
            except Exception as e:
                print(f"   ❌ Email 寄送失敗: {e}")
        else:
            print("   ⚠️ 本批次沒有產生任何 PDF，跳過寄信。")

        # 休息一下再跑下一批，避免對網站造成負擔
        print("   (休息 5 秒後執行下一批...)")
        time.sleep(5)

    print("\n🎉🎉🎉 所有批次作業全部完成！ 🎉🎉🎉")

except Exception as e:
    print(f"讀取檔案或執行過程發生嚴重錯誤: {e}")

finally:
    driver.quit()